branch-defaults:
  master:
    environment: Ia7-env
    group_suffix: null
environment-defaults:
  Ia7-env:
    branch: null
    repository: null
global:
  application_name: IA7
  branch: null
  default_ec2_keyname: null
  default_platform: Node.js 12 running on 64bit Amazon Linux 2
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: eb-cli
  repository: null
  sc: git
  workspace_type: Application
